env:
  global:
  - secure: gy4hBR09/Ug2H5Okts2+hz3jdQrGpgcKLhERi/CHwxzaB+YE1ir1BAvKx2Qfn6bj7J+0OxW65weaWJiVRcibXwIGaXAuWHDSbW/Emzcidw5a6XSi61JA1NTmcvrSA+Vw+7a0CeHiOpPDdtWySIGJSAgTbFxCh983LWOg9maCiwy9JKObG86Ha0j3SgRuSaFMszUalzzJGc2zhTW5qxpQNarcyV+WkqI67xzCBi9dGOVc/C2cvxt91bz/peib+qSIIDmzvdrG3tiQS4LybkAXfBFR4bogjs7n9l4oclE+l7Wij435N9Zk9j20sZ2A1ZihqhY44wwXRmcpPVdyrvW5VALl55yW9nSN1x6JZ1hOvU0Rk38WLercse0XYlvBxsoHi5ixn0+BJP4vLFOqJTUzR/0IRPqeeHI+ldDt45ul6MzaiPxjkvAeQn9Sr0ARFdjK4CQ9iU8NyOsdmZhiYuATTqhrs0xJ66rPqVccMwKh/TEixVfHv27ZRqrNXfpU4DtfdJY3JmV5obREPUa8HSwy4uTba5x7q1AG3Q1zDdv+ncGUmacMjWgWRp2PXE6VJngerycBO44Pysdn/y4sZzat52XLzBap+jPnd+s1G6pePPfT/f7GZM3lQM7J1xCfmAfkbhll4lxfny/3Hw+9LiVmjqpDDHu9Jy+DI12LBDvgq2g=
  - secure: I6cfCe9MDlrKebKRSXCPkHv9L1e16qQNiVXXzDsB1m4DcNJFChr2NnChA8ssHSE8Mw/xz/1wLNao7smngrjzMIFzIb2jIU+LW1aD527XXbueMV6GrkqsHt32pJmijNqvUaslPbOcqPn8ezdNOzZ9dp/RntRSX4V/9WuKo9SjHnPqiuayikFIaSI66Ar95Saww5Ojljidp8k0fSobVpyQaCpJZr9GIyMQAoQUMo4Uel/0eRTjHY+/dnZ+PuVn66FOJUnHPKLZk4JcrfPGKSjURIb9u+A6kAbRmCUo0LxG3a/zz/nHKv+K9yL8n1Xx1iw4Q6CPQ0xt5QP0bTXTkFCohElXT7abiG2ix3BKrFO5wrlKfOujiKj5eJC0aiRBxbmbXblpGbaUjHklv44FNCpZfCOqvspsnAUS7/WzOogITN4ODOWrridZ6IRPgk7zPScXt0pY85/jHOQlqSY90r12Lkq+7xblruk43/W0Dq3wY8gdOR7F0ivOzAvFmGuATXZOKEb8RJSB5jEs7vzZL52kyIzttzz1DWnm+538cbWVzjLfhDiIe+RtqU0JyaG5p6viiVTfNaYohTudw5Ijmv/cxhp7enPfOUR4cmYBbGIx9YmF0+rQUUcZJBzlfIlyHf5axGKyYAJYJTrek9TlSPr6ga+gFhTH5YVLpZ+n46KVKDs=
addons:
  sauce_connect: true
language: node_js
node_js:
- 0.10
- 0.11
- 0.12
- 4
- 5
- 6
- iojs
script:
- './bin/nahual --target saucelabs -a local -- python -m SimpleHTTPServer'
- './bin/nahual --target saucelabs -a remote'
- 'npm run cover'
after_success:
- 'npm run cover:up'
